### ISSUE TITLE
ブラウザから直接閲覧を行いたい

### ISSUE THREAD

**Issue by osyo-manga** [EzoeRyou/cpp-book#1]
gh-pages を使用すればブラウザから直接HTMLをレンダリングすることができるのですが、いかがでしょうか。
gh-pages を使用すると[このようにアクセ](http://osyo-manga.github.io/cpp-book/C++11-Syntax-and-Feature.xhtml)する事ができます。
- 参考
  - http://hisasann.com/housetect/2012/02/githubgh-pages.html
  - http://www.ne.jp/asahi/hishidama/home/tech/git/gh-pages.html

**Comment by EzoeRyou** [comment]
さて、どうやるのかな。

**Comment by osyo-manga** [comment]
branch/gh-pages を作成して push を行うだけなので作業自体はすぐに終わると思います。

``` shell```
$ git branch gh-pages
$ git checkout gh-pages
$ git push -u origin gh-pages
```

これで大丈夫だと思います。
ただし、設定が反映されるまで時間がかかるかもしれません。
（わたしの場合だと10分ほど時間がかかると言われました

**Comment by EzoeRyou** [comment]
こうか。

**Comment by osyo-manga** [comment]
http://ezoeryou.github.io/cpp-book/C++11-Syntax-and-Feature.xhtml から閲覧ができることを確認しました。
ありがとうございます！

**Comment by EzoeRyou** [comment]
これ、http://ezoeryou.github.io/cpp-book/だけで表示するにはどうすりゃいいのかね。

**Comment by osyo-manga** [comment]
うーん、`C++11-Syntax-and-Feature.xhtml` を `index.xhtml` にリネームするとかでしょうか。
そこまで詳しくないのでちょっとわからないです…。

**Comment by xuwei-k** [comment]
おそらく `index.html` にリネームするしかないでしょうね。
別に`index.html`作って、そこからリダイレクトという方法もありますが、挙動違いますし。

あと話変わりますが、`gh-pages` の branch があってそれが `master` と同じならば、`master` の branch 自体を削除して、今後 `gh-pages` だけ更新していけばいい気がします。
2つbranchがあって、今後も全く同じ内容で更新していく予定なら、commitの手間が増えるだけで、branchが2つある利点がほぼないので。

**Comment by EzoeRyou** [comment]
ああ、そうか。gh-pagesだけでいいか。
