### ISSUE TITLE
decltype解説で、c.value はpublicか？

### ISSUE THREAD

**Issue by inouaTI** [EzoeRyou/cpp-book#130]
【14496行】
class C {
public:                         //←必要か？
    int value ;
} ;
C c ;
// decltype(c)の型は、class C
decltype(c) t2 ;
// decltype(c.value)の型は、int
decltype(c.value) t3 ;               //←エラーが出る

publicの説明ではないのでどうでもよいのかもしれない。間違えたことだったらごめんなさい。
初投稿です。不備が有ったらごめんなさい。

**Comment by EzoeRyou** [comment]
本書ではアクセス指定は問題の本質ではないために、ほとんどstructを使っていたクセがでてしまったようです。
ここはclassのまま、public:を付け加えておきます。
