### ISSUE TITLE
8.2 曖昧解決（Ambiguity resolution）

### ISSUE THREAD

**Issue by inouaTI** [EzoeRyou/cpp-book#132]
8.2 曖昧解決（Ambiguity resolution）
 略
    S y( static_cast<int>(d) ); // S型の変数yの宣言　　　← <int>　かな？
    S z = int(d); // S型の変数zの宣言
}

---------<別件で私の意見＞--------
2.7 キーワード（Keywords）　項目で、
キーワードをアルファベット順に並べてほしい。（実は並べてあるが）
一見ランダムに並べてあるようにみえる。（TAB位置に揃えるとか、表にするとか）
初心者の目次は、キーワードからだと思う。
できればキーワードの説明位置にリンクして欲しい。
私のC言語辞典は手垢がいっぱい付いている。
（欲を言うと、本の最後に用語の索引が有るといいな）

**Comment by EzoeRyou** [comment]
できれば問題点を文章で指摘してください。
なるほど、確かにstatic_castに形名が抜けてますね。

キーワードは、同じキーワードに複数の機能が割り当てられている場合もあるのです。
テーブルにして主要機能へのリンクを貼ることは便利かもしれませんね。
すこし考えてみます。

**Comment by EzoeRyou** [comment]
おっと、また解決じゃなかった。

**Comment by inouaTI** [comment]
私の場合はCのキーワードから検索を初めます。
初心者はこの本の目次は難しいか、目的語を探しだすのに時間がかかると思うのです。
この本は上級者向けのように思いますが。
検索機能を使えば全部解決するのですが、これもわからない人はなかなかたどり着けないと思うのです。私も。
私はこの本を辞書代わりに使いたい。できるだけ早く目的語を見つけたい。何度も何度も検索機能を使うと思うのです。
初心者（使っている期間は長いが）の意見でした。

**Comment by EzoeRyou** [comment]
私が単一のXHTMLファイルにしたのは、移植性が高いことと、単純なテキストを扱うツールでも処理できることと、全文検索が容易なことからです。

**Comment by EzoeRyou** [comment]
キーワードからリンクを貼ります。
まだ終わってません。

**Comment by inouaTI** [comment]
ついでにと言ったら何ですが、誤植の報告。
8.3 宣言子の意味（Meaning of declarators）

// 識別子aはint型の変数
int     // 指定子
a ;     // 宣言子、
// 識別子bはint型のtypedef名      ← cでは？
typedef int // 指定子
c ;         // 宣言子

全部ひと通り読もうと思っていて、今ここです。半分位か。
