### ISSUE TITLE
Visual Studio12 のみの動作なのか？　（ここに書いても良いか迷ったが）

### ISSUE THREAD

**Issue by inouaTI** [EzoeRyou/cpp-book#134]
<pre>
----------
8.3.2 リファレンス（References）

void f( int obj )
{
    int const & a = obj ; // OK、int constへのリファレンス

    //■ Visual Studio12 で「warning C4227: 旧形式が使用されています : 参照の修飾子は無視されます。」 警告となる。
    int & const b = obj ; // エラー、リファレンスへのCV修飾はできない
}
----------
----------
8.3.2 リファレンス（References）
void f()
{
    int * ptr = nullptr ;

    //■ Visual Studio12 ではエラーにならない。
    int & ref = *ptr ; // エラー、nullポインターを参照している
}
----------
</pre>

**Comment by EzoeRyou** [comment]
MSVCはC++の規格準拠度が極めて低く、C++のソースコードの検証用には不適です。
というより、MSVCはどんな用途にも不適なのですが。

本書の特定のC++実装に依存して書かれてはいないので、本書の規格違反の検証には、C++規格、N3337を参照するべきです。
コンパイラーが必要であれば、GCCかClangの最新のバージョンを利用すべきです。

その例でいうと、1つ目はMSVCが規格に準拠していないためです。
2つ目は、本書では便宜上「エラー」としていますが、実際には、「挙動が未定義」なのです。
挙動が未定義の場合、鼻から悪魔が召喚されたり、コンパイラーがにわかにnethackを立ちあげてゲームを始めても文句を言えません。

**Comment by inouaTI** [comment]
説明有難うございます。
現在の環境以外は殆ど知らないので自分が何を言うかわからないな、と言う感じでいます。
大昔に遊びでGCCをWindowsでBTRON(トロンOS)とITRON(組込OS)のクロス開発環境で1年位触った事が有る程度です。
能力がないので手を広げないで行こうと思っています。

**Comment by EzoeRyou** [comment]
最近はSaaSSではありますが、オンラインで短いコードを送ってコンパイルして実行して結果を知らせてくれるようなサービスもあります。
レポジトリ最新のGCCやClangのビルドもあるので、単にC++の文法の検証用には、十分でしょう。

http://melpon.org/wandbox/

**Comment by inouaTI** [comment]
うわぁ、出来た(^_^)　GCC
#include <iostream>

int main()
{
     std::cout << "hello world" << std::endl;
}
こんな環境が有るんですね。
感激しています。
昔のことはほとんど忘れたが、そう言えばRS232Cケーブルで出来たプログラムを転送、実行していたような覚えが。
itis（イットイズ） と言うOSが有ったような。
2年とか、5年とかプログラムをしない時が有るからプログラムで遊び始める時はいつも1年生。
有難うございます。

**Comment by EzoeRyou** [comment]
コンパイラーのバージョン間の違いを調べるのにも重宝しますよ。
