### ISSUE TITLE
cpp-bookについての要望

### ISSUE THREAD

**Issue by inouaTI** [EzoeRyou/cpp-book#137]
・ページ番号が欲しい。
・・理由1：ブラウザの幅を変えると、読んでいる位置が変わって分からなくなる。（巨大な１ページ物だから）
・・理由2：ページ番号を控えておいて後日続きを読むため。その他。
　　（出来れば「しおり」機能が有ればよいのだけど）

**Comment by EzoeRyou** [comment]
そもそもページという単位は、もう古臭いものだと思うのですが。
あれはきっちり組版して紙に印刷する都合上、しかたなく存在するものです。
動的にリアルタイムでリフローできる環境では、ページの必要性がなくなります。

**Comment by inouaTI** [comment]
はい。了解です。
有ると現在の位置が分かって良いかなと思ったもので。すごい量なもので。
使い込んでいないので分からないけど言ってみました。

**Comment by EzoeRyou** [comment]
ページ内にidでリンクが貼られているので、
例えば、
C++11-Syntax-and-Feature.xhtml#expr.prim.lambda
とすればlambda式に飛べたりとかはできますが。

**Comment by inouaTI** [comment]
わかりません。
ブラウザのページ内検索に”C++11-Syntax-and-Feature.xhtml#expr.prim.lambda”と入れるのでしょうか？

**Comment by EzoeRyou** [comment]
HTMLでは、ページ内のid属性に、URLの後に#<id属性の値>で飛べるのです。
例えば以下のようにですね。

http://ezoeryou.github.io/cpp-book/C++11-Syntax-and-Feature.xhtml#expr.prim.lambda

#139 をマージしましたので、スクロールしたところのidへのリンク、自動的にブラウザーのアドレスバーのところに表示されるはずです。
読んでいるところでブラウザーのアドレスバーに表示されているURLを覚えておけば、あとで戻れますよ。

**Comment by inouaTI** [comment]
出来ました。戻れました。
いつも有難うございます。

**Comment by EzoeRyou** [comment]
これにて解決
