### ISSUE TITLE
コメント追加　8.5.3 （このissuesは間違っているかもしれない）

### ISSUE THREAD

**Issue by inouaTI** [EzoeRyou/cpp-book#143]
【グローバル空間ではエラーになる new int()】

8.5.3 値初期化（value-initialize）

空の()を書く事ができる初期化子には、5.5.3 関数形式のキャスト、5.6.4 new、12.6.2 メンバー初期化がある。

<pre>
  // 関数形式のキャスト
 int x = int() ;
 // new
【18122行】
- new int() ;
+ new int() ; // グローバル空間ではエラーになる　←

 // メンバー初期化
 class C
 {
    int member ;
    C() : member()
    { }
 } ;
</pre>

**Comment by EzoeRyou** [comment]
修正

**Comment by inouaTI** [comment]
上記ソース欄の下のソース欄で、

<pre>
int x{} ; // int型の変数xの宣言と定義と初期化子
int y({}) ; // int型の変数yの宣言と定義と初期化子
</pre>

int y({}); がエラーになる成るのですが、なぜでしょうか？(Wandbox:clang)

**Comment by inouaTI** [comment]
このソース欄の　S({ 1, 2, 3 }) ; 　はエラーにならない。

コンストラクター呼び出しの実引数

【19048行】

<pre>
#include <initializer_list>
struct S
{
    S( std::initializer_list<int> ) { }
} ;
int main()
{
    S s1( { 1, 2, 3 } ) ;
    S s2{ 1, 2, 3 } ;
    S({ 1, 2, 3 }) ; // 関数形式のキャスト　　　　←正常
    S{ 1, 2, 3 } ; // 関数形式のキャスト
}
</pre>

**Comment by inouaTI** [comment]
<pre>
int m2[3]( { 1, 2, 3 } ) ;　エラーに成る。
</pre>

非staticデータメンバーの初期化子

【19072行】

<pre>
struct S
{
    int m1[3] = { 1, 2, 3 } ;
    int m2[3]( { 1, 2, 3 } ) ;　　　←エラーに成る
    int m3[3]{ 1, 2, 3 } ;
} ;
</pre>

**Comment by inouaTI** [comment]
<pre>
S() : data( { 1, 2, 3 } ) { }    エラーに成る
</pre>

メンバー初期化子

【19087行】

<pre>
struct S
{
    int data[3] ;
    // 以下二行は同じ意味
    S() : data{ 1, 2, 3 } { }
    S() : data( { 1, 2, 3 } ) { }             ←エラーに成る
} ;
</pre>

**Comment by EzoeRyou** [comment]
残りを見逃していたのでreopen。
明日に確認します。
別の問題は、できれば異なるissueを作ってください。
単に位置が近いからといって同じissueのコメント欄に複数書かれると、見落とします。

**Comment by EzoeRyou** [comment]
すでにcloseしたissueのコメントであらたな問題を書かれても、見落とします。
他にも、closeしたあとにコメントで問題を報告していて、未だに何の反応もない場合、見落としている可能性があります。
遠慮せずに、一つの問題ごとに新しいissueを作ってください。

**Comment by EzoeRyou** [comment]
また、問題がcloseされても正しく修正されていない場合は、新たにissueを追加するか、reopenしてください(そのレポジトリ以外のユーザーがreopenできたかな？)

**Comment by inouaTI** [comment]
了解しました。

**Comment by EzoeRyou** [comment]
あー、このへんは当時のドラフトと文面が変わったのかな。
