### ISSUE TITLE
static が不要か

### ISSUE THREAD

**Issue by inouaTI** [EzoeRyou/cpp-book#144]
static が不要か

8.5.4 アグリゲート（Aggregates）

<pre>
 struct S
 {
    int x ;
    static int static_data_member ; // staticデータメンバー
    int y ;
    int : 8 ; // 無名ビットフィールド
    int z ;
 } ;
【18460行】
- static int S::static_data_member ;
+        int S::static_data_member ;

 S s = { 1, 2, 3 } ;
 // s.x = 1, s.y = 2, s.z = 3
</pre>

この例では、static_data_memberと、yとzとの間にある無名ビットフィールドは、リスト初期化の際には、メンバーとして考慮されない。

**Comment by EzoeRyou** [comment]
おおっと、これは恥ずかしい。
