### ISSUE TITLE
エラーにならない　？

### ISSUE THREAD

**Issue by inouaTI** [EzoeRyou/cpp-book#150]
コードを打ち込んだらエラーにならない所がある。
３ヶ所。
難しくなって、内容をまだ理解していない。

10.3 virtual関数（Virtual functions）

<pre>
struct Base { } ; // 基本クラス
struct Derived : Base { } ; // 派生クラス
struct Other { } ; // BaseやDerivedとは派生関係にないクラス

// クラスが同じ
struct B { virtual Base &amp; f() ; } ;
struct D : B { virtual Base &amp; f() ; } ;

// B::fのクラスはD::fのクラスの基本クラス
struct B1 { virtual Base &amp; f() ; } ;
struct D1 : B { virtual Derived &amp; f() ; } ;

// エラー
【21972行】 エラーにならない
struct B2 { virtual Derived &amp; f() ; } ;    　　 ←正常
struct D2 : B { virtual Base &amp; f() ; } ;  　　  ←正常

// エラー
struct B3 { virtual Base &amp; f() ; } ;       　　  ←正常
struct D3 : B { virtual Other &amp; f() ; } ;  　  ←これのみエラーに成る？
</pre>

**Comment by tzik** [comment]
BをB2やB3に置き換え忘れているようにみえます。

> struct D2 : B { virtual Base & f() ; } ;

**Comment by inouaTI** [comment]
ごめんなさい。間違えていました。

struct D1 : B{ virtual Derived &f(); };
BをB1に変更していませんでした。
指摘していただいたように下記に変更したら、解説どうり（エラー）に成りました。
やはりまだ理解していなかった。

<pre>
struct Base{};
struct Derived : Base{};
struct Other{};
struct B { virtual Base &f(); };
struct D : B { virtual Base &f(); };
struct B1 { virtual Base &f(); };
struct D1 : B1 { virtual Derived &f(); };
//エラー
struct B2 { virtual Derived &f(); };
struct D2 : B2 { virtual Base &f(); };
//エラー
struct B3 { virtual Base &f(); };
struct D3 : B3 { virtual Other &f(); };
</pre>

**Comment by inouaTI** [comment]
この場合、BとDの関数について説明しているから、BをB1に変えてコードを読んだって、実行したって解説を理解するのに何の意味もないと言うか、そんな事をしたら余計に読みにくく成るんですね。アクセスできるか、を見なければならないのに。
