### ISSUE TITLE
{ } の記入漏れ４ヶ所

### ISSUE THREAD

**Issue by inouaTI** [EzoeRyou/cpp-book#152]
{ } の記入漏れ４ヶ所。

12.6.1 明示的な初期化（Explicit initialization）

【24990 行】

<pre>
　struct X
　{
-    X( int ) ;
+    X( int ) { }
-    X( int, int ) ;
+    X( int, int ) { }
-    X( int, int, int ) ;
+    X( int, int, int ) { }
　} ;

　int main()
　{
    X x1( 1 ) ; // X::X(int)
    X x2( 1, 2 ) ; // X::X(int,int)
    X x3( 1, 2, 3 ) ; // X::X(int,int,int)
　}
</pre>

詳しくは、初期化子の直接初期化を参照。

また、=（イコール）記号に続いて値を指定することで、初期化することもできる。

<pre>
　struct X
　{
-    X( int ) ;
+    X( int ) { }
　} ;

　int main()
　{
    X x = 0 ; // X::X(int)
　}
</pre>

**Comment by EzoeRyou** [comment]
それは意図的なものです。
定義というのは、実行時のことで、コンパイル時にはとくに関係がありません。

On 11/21/13, inouaTI notifications@github.com wrote:

> { } の記入漏れ４ヶ所。
> 
> 12.6.1 明示的な初期化（Explicit initialization）
> 
> 【24990 行】
> 
> <pre>
> 　struct X
> 　{
> -    X( int ) ;
> +    X( int ) { }
> -    X( int, int ) ;
> +    X( int, int ) { }
> -    X( int, int, int ) ;
> +    X( int, int, int ) { }
> 　} ;
> 　int main()
> 　{
>     X x1( 1 ) ; // X::X(int)
>     X x2( 1, 2 ) ; // X::X(int,int)
>     X x3( 1, 2, 3 ) ; // X::X(int,int,int)
> 　}
> </pre>
> 
> 詳しくは、初期化子の直接初期化を参照。
> 
> また、=（イコール）記号に続いて値を指定することで、初期化することもできる。
> 
> <pre>
> 　struct X
> 　{
> -    X( int ) ;
> +    X( int ) { }
> 　} ;
> 　int main()
> 　{
>     X x = 0 ; // X::X(int)
> 　}
> </pre>
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/EzoeRyou/cpp-book/issues/152

## 

Ryou Ezoe

Blog:     http://cpplover.blogspot.com/
Twitter: https://twitter.com/EzoeRyou
GitHub: https://github.com/EzoeRyou

**Comment by inouaTI** [comment]
「クラスのオブジェクトの初期化子には括弧に囲まれた式リストを使うことができる。この場合、適切な仮引数リストのコンストラクターによって初期化される。 」
の解説文で、
「この場合、適切な仮引数リストのコンストラクターによって初期化される。 」
という所の解説ですね。
済みませんよく読みませんでした。
