### ISSUE TITLE
実装依存の文字を使った識別子

### ISSUE THREAD

**Issue by mrdagon** [EzoeRyou/cpp-book#168]
半ば質問ですが。

2.6 識別子（Identifiers）
で実装依存の文字として
int 変数;
とサンプルコードにありますが、プリプロセスでUCNに変換されるため"変数"と言う文字が識別子に使えるかはソースコードのエンコーディングにUTF-8等を認めているかどうかの問題のはずです。
規格書を読むと実装依存の文字とは$や@等を指しているとも解釈出来ます。
大体のC++コンパイラでは$が識別子に使えるようですし。
int $variable$;
とするのが正しいのではないかと思うのですがどうなんでしょうか？

**Comment by EzoeRyou** [comment]
Unicodeに規定されている文字ならば、Phase of translationでUCNに変換されて処理されます。
すなわち、

int \U00005909\U00006570 ;

に変換されます
これはこのように規定されているので、C++の実装は、観測可能なところではこの挙動にならなければなりません。
規格準拠の実装は、Unicode文字をサポートしなければなりません。

**Comment by mrdagon** [comment]
どうもです。
　AnnexEで$記号が許可されていないのに使える実装が多いので、other implementation-defined characters は AnnexEに入っていない文字を独自に定義して良いと言う意味かと思ったのですが。
　other implementation-defined charactersは補足説明に入っているだけであり、$はill-formedなので使うなと言う事ですね。

**Comment by EzoeRyou** [comment]
ill-formedではありません。
もし、実装がサポートしていれば使えますし、Unicode文字ならば使えます。
＄はUnicode文字に入っているので、（規格上は）、使えます。

ただ、現実での移植性を考えると、基本文字セットの範囲外の文字は、識別子などには避けておいたほうが賢明でしょう。

**Comment by mrdagon** [comment]
ありがとうございます
半角の方の$はill-formedかと思ったんですが、何にせよ使わない方が良さそうですね。
　実際、clangでコンパイルが通ったのにアセンブラがエラーを出すぐらい移植性が下がるのですが、識別子にルー語を使うのは楽しいので辞められそうにないです…
