### ISSUE TITLE
コードの例示を示すコロンの有無

### ISSUE THREAD

**Issue by watiko** [EzoeRyou/cpp-book#186]
``` html
<p>
アクセス指定子によりクラスのデフォルトコンストラクターからは利用できない場合の例
</p>
```

``` html
<p>
コンストラクターに関数tryブロックを使う例：
</p>
```

これに関しても基準があると好いです。

**Comment by EzoeRyou** [comment]
英語圏ではよくある表現で、影響されて書いている場合もありますが、日本語の場合には、コロンを使うのはなじまないのでないほうがいいのではないかと。いずれにせよ、長期間編集している文章なので、いろいろ一貫しない部分が出てきています。
