### ISSUE TITLE
ラムダ式の戻り値型の推測について

### ISSUE THREAD

**Issue by yohe** [EzoeRyou/cpp-book#30]
「ラムダ式の基本的な使い方」で記載されている以下のサンプルについて。
エラーで記載されている例は OK ではないでしょうか。
"return x ;"は lvalue から rvalue への型変換が適用されて戻り値の型はint?
試してみたらコンパイルは通るようです。

<pre>
// エラー、戻り値の型はvoidだが、値を返している
[]
{
    int x = 0 ;
    return x ;
}() ;

// OK、戻り値の型を、明示的に指定している。
[] -> int
{
    int x = 0 ;
    return x ;
}() ;
</pre>

**Comment by EzoeRyou** [comment]
それはC++11ではなくて、C++14です。

**Comment by EzoeRyou** [comment]
C++11では、ラムダ式の戻り値の型が推定されるためには、本体はreturn文ひとつでなければなりません。

**Comment by yohe** [comment]
そうだったんですね。
ご回答ありがとうございました。
Close します。
