### ISSUE TITLE
5.20 代入と複合代入演算子 複合代入演算子の説明

### ISSUE THREAD

**Issue by kariya-mitsuru** [EzoeRyou/cpp-book#33]
複合代入演算子の説明に「opには、任意の複合代入演算子が入る。」とあるのですが、「op=」が複合代入演算子なのでちょっと説明がおかしい気がします。
「op」を示す言葉が思い浮かばないのですが…

**Comment by EzoeRyou** [comment]
うーん・・・これは参考書としての簡略化のせいですね。いまいちいい言い方も思い浮かばないのですが。

**Comment by EzoeRyou** [comment]
まあ、細かいですが、「任意の複合代入演算子の一部が入る」と書き換え
